"""add appointment type and link

Revision ID: 4f9a8bca1923
Revises: e402e4eb0632
Create Date: 2026-02-09 23:30:37.786236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9a8bca1923'
down_revision: Union[str, Sequence[str], None] = 'e402e4eb0632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_type', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('meeting_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'meeting_link')
    op.drop_column('appointments', 'appointment_type')
    # ### end Alembic commands ###
