"""Add cascades

Revision ID: 657cd0e0bafb
Revises: ebf94e7c68b7
Create Date: 2026-02-16 23:29:16.979072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657cd0e0bafb'
down_revision: Union[str, Sequence[str], None] = 'ebf94e7c68b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_availabilities_doctor_id_fkey'), 'doctor_availabilities', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_availabilities', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('doctors_user_id_fkey'), 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key(op.f('doctors_user_id_fkey'), 'doctors', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'doctor_availabilities', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_availabilities_doctor_id_fkey'), 'doctor_availabilities', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
