"""add degree upload url

Revision ID: 9e26dbe013ea
Revises: f56220cb6b16
Create Date: 2026-02-08 17:09:51.741752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e26dbe013ea'
down_revision: Union[str, Sequence[str], None] = 'f56220cb6b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('degree_upload_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'degree_upload_url')
    # ### end Alembic commands ###
