"""add unique booking constraint

Revision ID: e402e4eb0632
Revises: 6e958721def0
Create Date: 2026-02-08 19:30:10.926251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e402e4eb0632'
down_revision: Union[str, Sequence[str], None] = '6e958721def0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_doctor_appointment_slot', 'appointments', ['doctor_id', 'appointment_date', 'appointment_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_doctor_appointment_slot', 'appointments', type_='unique')
    # ### end Alembic commands ###
