"""allow_cancelled_slots

Revision ID: ebf94e7c68b7
Revises: 4f9a8bca1923
Create Date: 2026-02-12 16:04:15.948158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf94e7c68b7'
down_revision: Union[str, Sequence[str], None] = '4f9a8bca1923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_doctor_appointment_slot'), 'appointments', type_='unique')
    op.create_index('uq_doctor_active_slot', 'appointments', ['doctor_id', 'appointment_date', 'appointment_time'], unique=True, postgresql_where=sa.text("status NOT IN ('CANCELLED', 'REJECTED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_doctor_active_slot', table_name='appointments', postgresql_where=sa.text("status NOT IN ('CANCELLED', 'REJECTED')"))
    op.create_unique_constraint(op.f('uq_doctor_appointment_slot'), 'appointments', ['doctor_id', 'appointment_date', 'appointment_time'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
